os: linux
dist: bionic

addon:
  apt:
    update: true

git:
  depth: 1

services:
  - docker

env:
  global:
    - IMAGE_NAME=alpine-android
    - IMAGE_TAG=x86_64

script:
  - "travis_wait 30 sleep 1800 &"
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build --rm --force-rm --compress -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG -f Dockerfile .

after_success:
  - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG && sleep 2
  - curl -X POST 'https://hooks.microbadger.com/images/fr3akyphantom/alpine-android/fQ9_Cx3nJ7z30FsuOV6ujHCaMfo=' && echo ''
